"""Ticket reservations: a reserved counter on ticket_types, plus orders and order_items.

ticket_types is live (created in the event catalog slice), so nothing here may rewrite it or hold
a long lock on it:
- ADD COLUMN with a constant default is metadata-only (PostgreSQL 11+).
- The CHECK is added NOT VALID (no scan) and validated in 0006, without blocking writes.

orders and order_items are new and have no traffic yet, so their indexes are created normally.

Revision ID: 0005_add_ticket_reservations
Revises: 0004_create_ticket_types
Create Date: 2026-10-06
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005_add_ticket_reservations"
down_revision: str | None = "0004_create_ticket_types"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("ticket_types", sa.Column("reserved", sa.Integer(), server_default="0", nullable=False))
    # The invariant that prevents overselling lives in the database, whatever the application does.
    op.execute(
        "ALTER TABLE ticket_types ADD CONSTRAINT ck_ticket_types_reserved_within_capacity "
        "CHECK (reserved >= 0 AND reserved <= capacity) NOT VALID"
    )

    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),  # UUIDv7, generated by the application
        sa.Column("buyer_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        # Orders are financial records that outlive accounts: deletion anonymizes the buyer instead.
        sa.ForeignKeyConstraint(["buyer_id"], ["users.id"], name=op.f("fk_orders_buyer_id_users"), ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], name=op.f("fk_orders_event_id_events"), ondelete="RESTRICT"),
        # A retried POST /v1/orders with the same Idempotency-Key can't create a second order.
        sa.UniqueConstraint("buyer_id", "idempotency_key", name=op.f("uq_orders_buyer_id_idempotency_key")),
        sa.CheckConstraint("status IN ('pending', 'paid', 'expired', 'cancelled')", name=op.f("ck_orders_status_valid")),
        sa.CheckConstraint("total_cents >= 0", name=op.f("ck_orders_total_non_negative")),
        sa.CheckConstraint("char_length(currency) = 3", name=op.f("ck_orders_currency_iso")),
        sa.CheckConstraint(
            "status <> 'cancelled' OR cancelled_reason IS NOT NULL", name=op.f("ck_orders_cancelled_reason_required")
        ),
    )
    # GET /v1/me/orders: WHERE buyer_id = :me ORDER BY created_at DESC, id DESC.
    # buyer_id already leads this index and the unique constraint, so the FK needs no index of its own.
    op.create_index(op.f("ix_orders_buyer_id_created_at"), "orders", ["buyer_id", "created_at", "id"])
    # Organizer sales list: WHERE event_id = :id [AND status = :s] ORDER BY created_at DESC, id DESC.
    op.create_index(op.f("ix_orders_event_id_created_at"), "orders", ["event_id", "created_at", "id"])
    # Stale-hold reaper: WHERE status = 'pending' AND expires_at < now(). Partial: pending is a small slice.
    op.create_index(
        op.f("ix_orders_expires_at_pending"),
        "orders",
        ["expires_at"],
        postgresql_where=sa.text("status = 'pending'"),
    )

    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_type_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("order_id", "ticket_type_id", name=op.f("pk_order_items")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["ticket_type_id"],
            ["ticket_types.id"],
            name=op.f("fk_order_items_ticket_type_id_ticket_types"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint("quantity BETWEEN 1 AND 10", name=op.f("ck_order_items_quantity_range")),
        sa.CheckConstraint("unit_price_cents >= 0", name=op.f("ck_order_items_unit_price_non_negative")),
    )
    # Deliberately no index on order_items.ticket_type_id: nothing filters items by ticket type
    # (sales counts come from ticket_types.reserved), and only draft ticket types without orders are
    # ever deleted, so the RESTRICT check stays cheap. The primary key serves "items of an order".


def downgrade() -> None:
    op.drop_table("order_items")
    op.drop_table("orders")
    op.execute("ALTER TABLE ticket_types DROP CONSTRAINT ck_ticket_types_reserved_within_capacity")
    op.drop_column("ticket_types", "reserved")
